# Generated by Django 6.1 on 2026-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_adminotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
    ]
