# Generated by Django 5.1.15 on 2026-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_adminotp_attempts_alter_adminotp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
